apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-flask-demo-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-flask-demo-prod # Add this label
  template:
    metadata:
      labels:
        app: eks-flask-demo-prod
    spec:
      containers:
      - name: eks-flask-demo-prod
        image: {{.Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
