apiVersion: v1
kind: Service
metadata:
  name: eks-flask-demo
spec:
  selector:
    app: eks-flask-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Match the port where your Go application is running
