apiVersion: v1
kind: Service
metadata:
  name: eks-flask-demo-a
spec:
  selector:
    app: eks-flask-demo-a
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080 # Match the port where your Go application is running
