apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-flask-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-flask-test # Add this label
  template:
    metadata:
      labels:
        app: eks-flask-test
    spec:
      containers:
      - name: eks-flask-test
        image: {{.Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
