apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'eks-flask-demo'
spec:
  destination:
    name: 'in-cluster'
    namespace: eks-flask-demo
  source:
    repoURL: 'https://github.com/LiboMa/codedemos.git'
    path: 'charts'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
