apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'eks-flask-demo'
  namespace: argocd
spec:
  destination:
    name: 'in-cluster'
    namespace: eks-flask-demo
    # server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/LiboMa/codedemos'
    path: 'chartDev/prod'
    targetRevision: master
    helm:
      valueFiles:
      - values.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
